import React, { useEffect, useState } from 'react';
import { api } from '../../api/client';

const COMPANY={company_name:'Название компании',company_inn:'ИНН / РМА',company_address:'Юридический адрес',company_phone:'Телефон',company_bank:'Банк',company_account:'Расчётный счёт',director_name:'Руководитель',accountant_name:'Главный бухгалтер',cashier_name:'Кассир',branch_name:'Филиал по умолчанию'};
export function CompanySettingsTab({section='company'}){
  const [row,setRow]=useState(null),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[history,setHistory]=useState([]);
  useEffect(()=>{Promise.all([api.get('/document-settings/configuration'),api.get('/document-settings/configuration/history')]).then(([r,h])=>{setRow(r.data.settings);setData({company:{},numbering:{},reservation_days:3,max_discount_percent:100,builders:[],branches:[],...r.data.settings.data});setHistory(h.data.history);}).catch(e=>setError(e.message));},[]);
  async function save(){setBusy(true);setError('');setMessage('');try{const r=await api.put('/document-settings/configuration',{version:row.version,data});setRow(r.data.settings);setData(r.data.settings.data);setMessage('Настройки сохранены.');const h=await api.get('/document-settings/configuration/history');setHistory(h.data.history);}catch(e){setError(e.message);}finally{setBusy(false);}}
  const field=(label,value,onChange,type='text')=><label key={label} className="text-sm">{label}<input className="mt-1 w-full border rounded-xl px-3 py-2" type={type} value={value??''} maxLength={type==='text'?500:undefined} onChange={e=>onChange(type==='number'?Number(e.target.value):e.target.value)}/></label>;
  return <div className="space-y-4">{error&&<p role="alert" className="bg-red-50 text-red-700 p-3 rounded-xl">{error}</p>}{message&&<p role="status" className="bg-green-50 text-green-700 p-3 rounded-xl">{message}</p>}{data&&<>
    {section==='company'&&<><h2 className="font-bold text-lg">Реквизиты и подписанты</h2><p className="text-sm text-slate-500">Используются в загруженных бланках Word. Пустое поле оставляет значение документа, если оно доступно.</p><div className="grid sm:grid-cols-2 gap-4">{Object.entries(COMPANY).map(([k,label])=>k==='branch_name'&&data.branches.length ? <label key={k} className="text-sm">{label}<select className="mt-1 w-full border rounded-xl px-3 py-2" value={data.company[k]||''} onChange={e=>setData({...data,company:{...data.company,[k]:e.target.value}})}><option value="">Не выбран</option>{data.branches.map((b,i)=><option key={i} value={b.name}>{b.name}</option>)}</select></label> : field(label,data.company[k],v=>setData({...data,company:{...data.company,[k]:v}})))}</div></>}
    {section==='numbering'&&<><h2 className="font-bold text-lg">Нумерация новых документов</h2><p className="text-sm text-slate-500">Пустая маска сохраняет текущую нумерацию. Обязательная переменная {'{id}'} или {'{id4}'} даёт уникальный номер. {'{id4}'} — номер с ведущими нулями, {'{year}'} — год даты документа. Для договора также доступны {'{project_code}'}, {'{building}'}, {'{unit}'}. Номера существующих документов сохраняются.</p><div className="grid gap-4">{Object.entries({CONTRACT:'Договор',PKO:'ПКО',RKO:'РКО'}).map(([k,label])=><div key={k}>{field(label,data.numbering[k],v=>setData({...data,numbering:{...data.numbering,[k]:v}}))}<p className="text-xs text-slate-500 mt-1">Пример: {(data.numbering[k]||'{id4}').replaceAll('{id4}','0123').replaceAll('{id}','123').replaceAll('{year}','2026').replaceAll('{project_code}','TOZON').replaceAll('{building}','A').replaceAll('{unit}','7')}</p></div>)}</div></>}
    {section==='rules'&&<><h2 className="font-bold text-lg">Скидки и бронирование</h2><p className="text-sm text-slate-500">Правила проверяются сервером при создании новой сделки. Срок брони применяется, если дата окончания не указана.</p><div className="grid sm:grid-cols-2 gap-4">{field('Максимальная скидка, %',data.max_discount_percent,v=>setData({...data,max_discount_percent:v}),'number')}{field('Срок брони по умолчанию, дней',data.reservation_days,v=>setData({...data,reservation_days:v}),'number')}</div></>}
    {['builders','branches'].includes(section)&&<><h2 className="font-bold text-lg">{section==='builders'?'Строительные компании':'Филиалы компании'}</h2><p className="text-sm text-slate-500">Справочник компании. Застройщика можно выбрать при создании ЖК; филиал — в реквизитах для бланков.</p>{data[section].map((item,i)=><div key={i} className="rounded-xl border p-4 grid sm:grid-cols-2 gap-3">{Object.entries({name:'Название',...(section==='builders'?{inn:'ИНН / РМА'}:{}),address:'Адрес',phone:'Телефон'}).map(([k,label])=>field(label,item[k],v=>setData({...data,[section]:data[section].map((x,j)=>j===i?{...x,[k]:v}:x)})))}<button className="text-red-600 text-sm text-left" onClick={()=>setData({...data,[section]:data[section].filter((_,j)=>j!==i)})}>Убрать из справочника</button></div>)}<button className="text-blue-600 text-sm" onClick={()=>setData({...data,[section]:[...data[section],section==='builders'?{name:'',inn:'',address:'',phone:''}:{name:'',address:'',phone:''}]})}>+ Добавить</button></>}
    <button disabled={busy} onClick={save} className="rounded-xl bg-blue-600 text-white px-5 py-2 disabled:opacity-50">{busy?'Сохранение…':'Сохранить настройки'}</button>
    <details className="border rounded-xl p-4"><summary className="font-bold cursor-pointer">История изменений настроек</summary>{history.map(h=><div key={h.id} className="border-t mt-3 pt-3 text-sm"><p>Версия {h.version} · {new Date(h.created_at).toLocaleString('ru-RU')} · Пользователь №{h.created_by}</p><button className="text-blue-600 mt-1" onClick={()=>{setData({company:{},numbering:{},reservation_days:3,max_discount_percent:100,builders:[],branches:[],...h.data});setMessage('Загружена предыдущая версия. Проверьте поля и нажмите «Сохранить настройки».');}}>Загрузить эту версию</button></div>)}</details>
  </>}</div>;
}
