import React, { useEffect, useState } from 'react';
import { api } from '../../api/client';
import { DOCUMENT_TYPES, DOCUMENT_LANGUAGES, downloadDocument } from './documentTemplates';

const DEMO={document_number:'ОБРАЗЕЦ-0001',document_date:'09.10.2026',contract_number:'0001',contract_date:'09.10.2026',client_name:'ТЕСТОВЫЙ КЛИЕНТ',unit_number:'1',area:'75',currency:'USD',contract_total:'75 000,00',schedules:[{row_number:1,due_date:'09.11.2026',planned_amount:'1 000,00',paid_amount:'0,00',balance:'1 000,00',status:'ОБРАЗЕЦ'}]};

export function DocumentTemplatesTab({projects=[]}){
  const [kind,setKind]=useState('CONTRACT'),[language,setLanguage]=useState('TJ'),[scope,setScope]=useState('*');
  const [templates,setTemplates]=useState([]),[fields,setFields]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  async function load(){const [t,c]=await Promise.all([api.get('/document-settings/templates'),api.get('/document-settings/configuration')]);setTemplates(t.data.templates);setFields(c.data.fields);}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  async function action(fn,success){setBusy(true);setError('');setMessage('');try{await fn();await load();setMessage(success);}catch(e){setError(e.message);}finally{setBusy(false);}}
  const versions=templates.filter(t=>t.kind===kind&&t.language===language&&t.scope===scope);
  const active=versions.find(t=>t.active);
  const common=templates.find(t=>t.kind===kind&&t.language===language&&t.scope==='*'&&t.active);
  async function upload(file){if(!file)return;await action(async()=>{const form=new FormData();form.append('file',file);form.append('kind',kind);form.append('language',language);form.append('scope',scope);await api.post('/document-settings/templates',form,{headers:{'Content-Type':'multipart/form-data'}});},'Бланк проверен и установлен. Предыдущая версия сохранена.');}
  return <div className="space-y-5">
    <div><h2 className="text-lg font-bold">Бланки документов</h2><p className="text-sm text-slate-500">Измените бланк в Word и загрузите DOCX. В карточке документа кнопка «Ваш бланк Word» заполнит его данными CRM. Для печати откройте полученный файл в Word.</p></div>
    <div className="grid sm:grid-cols-3 gap-3">{[[kind,setKind,DOCUMENT_TYPES,'Документ'],[language,setLanguage,DOCUMENT_LANGUAGES,'Язык'],[scope,setScope,{'*':'Все ЖК',...Object.fromEntries(projects.map(p=>[p.id,p.name]))},'Жилой комплекс']].map(([value,set,options,label])=><label key={label} className="text-sm">{label}<select className="mt-1 w-full rounded-xl border p-3" value={value} onChange={e=>set(e.target.value)}>{Object.entries(options).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>)}</div>
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{message&&<p role="status" className="rounded-xl bg-green-50 p-3 text-green-700">{message}</p>}
    <div className="rounded-2xl border bg-white p-5 space-y-4"><div><strong>{active?.name || (scope!=='*'&&common ? `Используется общий бланк: ${common.name}` : 'Используется встроенная печатная форма')}</strong><p className="text-xs text-slate-500 mt-1">До 2 МБ. DOCX без макросов, вложенных объектов и внешних ссылок. Шрифт, таблицы, поля страницы и логотип внутри файла сохраняются.</p></div>
      <div className="flex flex-wrap gap-3"><label className={`rounded-xl bg-blue-600 px-4 py-2 text-white text-sm cursor-pointer ${busy?'opacity-50':''}`}>{busy?'Обработка…':'Загрузить / заменить бланк'}<input aria-label="Загрузить бланк DOCX" disabled={busy} type="file" accept=".docx" className="hidden" onChange={e=>{upload(e.target.files?.[0]);e.target.value='';}}/></label>
      <button disabled={busy} className="border rounded-xl px-4 py-2 text-sm" onClick={()=>action(()=>downloadDocument(`/document-settings/sample/${kind}`,`TOZON-${kind}-sample.docx`),'Скачан технический образец с переменными. Замените текст вашим утверждённым бланком.')}>Скачать образец с переменными</button>
      {active&&<><button disabled={busy} className="border rounded-xl px-4 py-2 text-sm" onClick={()=>action(()=>downloadDocument(`/document-settings/render/${active.id}`,'TOZON-preview.docx',DEMO),'Скачан предварительный просмотр с тестовыми данными.')}>Проверить заполнение</button><button disabled={busy} className="border rounded-xl px-4 py-2 text-sm" onClick={()=>action(()=>api.post(`/document-settings/templates/${active.id}/disable`),'Бланк отключён. Будет использоваться общий бланк ЖК или встроенная форма.')}>Отключить</button></>}
      </div>
    </div>
    <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-bold">Переменные для Word и графика погашения</summary><p className="text-sm mt-3">Вставляйте переменную вместе со скобками, например {'{client_name}'} или {'{contract_number}'}. Для строк графика поместите {'{#schedules}'} и {'{/schedules}'} вокруг строки таблицы, а внутри — {'{due_date}'}, {'{planned_amount}'}, {'{paid_amount}'}, {'{balance}'}. Названия не переводятся.</p><div className="flex flex-wrap gap-2 mt-3">{fields.map(f=><button key={f} className="text-xs rounded bg-slate-100 px-2 py-1" onClick={()=>{navigator.clipboard?.writeText(`{${f}}`).then(()=>setMessage(`Скопировано: {${f}}`)).catch(()=>setMessage(`Переменная: {${f}}`));}}>{`{${f}}`}</button>)}</div></details>
    <div className="rounded-2xl border bg-white p-5"><h3 className="font-bold mb-3">История версий выбранного бланка</h3>{!versions.length&&<p className="text-sm text-slate-500">Загруженных версий пока нет.</p>}{versions.map(t=><div key={t.id} className="flex flex-wrap justify-between gap-3 border-t py-3"><div><strong className="text-sm">{t.name} {t.active&&'· Действующий'}</strong><p className="text-xs text-slate-500">{new Date(t.created_at).toLocaleString('ru-RU')} · {Math.ceil(t.file_size/1024)} КБ · Пользователь №{t.created_by}</p></div><div className="flex gap-3 text-sm"><button disabled={busy} onClick={()=>action(()=>downloadDocument(`/document-settings/templates/${t.id}/download`,`${DOCUMENT_TYPES[kind]}.docx`),'Бланк скачан.')}>Скачать</button>{!t.active&&<button disabled={busy} className="text-blue-600" onClick={()=>action(()=>api.post(`/document-settings/templates/${t.id}/activate`),'Версия восстановлена.')}>Восстановить</button>}</div></div>)}</div>
  </div>;
}
